import type { Metadata } from "next";
import EitaiGothicBold from "next/font/local";

import Image from "next/image";
import Logo from "../../public/logo.svg";
import { Geist, Geist_Mono, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { CircleIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
// import { Suspense } from "react";
// import { UserMenu } from "@/components/user-menu";
import Link from "next/link";
import { type ClassValue } from "clsx";
import Header from "@/components/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

const eitaiGothicBold = EitaiGothicBold({
  src: [
    {
      path: "../../public/fonts/KOT-Eitai Gothic Bold.ttf",
      weight: "700",
      style: "Bold",
    },
  ],
  variable: "--font-eitai-gothic-bold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${eitaiGothicBold.variable}`}>
      <body className={`${eitaiGothicBold.variable}`}>{children}</body>
    </html>
  );
}
